#!/bin/bash
# usage : cp2pest_loop pestpp_opt.pst

# clean destination directories
rm -rf ../pest/drone/*
rm -rf ../pest/queen/pest_files/*

# copy pest files to queen
cp -r ./pest_files/*.ins ../pest/queen/pest_files/
cp -r ./pest_files/*.tpl ../pest/queen/pest_files/

for i in {15..60..05}
do
	cp "0_$i""_""$1" ../pest/queen/
	cp prior_cov_matrix.jcb ../pest/queen/
	cp "0_$i""_""$1" ../pest/drone/
done

# copy model files to drone
for file in $(<model_files_loop.txt)
do
	cp -r "$file" ../pest/drone/
done

